from app.utility import clendar_utils

LUNCH_DURATION_MINUTES = 60
NETWORKING_DURATION_MINUTES = 60

LIGHTNING_DURATION_MINUTES = 5

TOTAL_TRACK_DURATION_MINUTES = 420
MORNING_SLOT_DURATION_MINUTES = 180
AFTERNOON_SLOT_DURATION_MINUTES = 240

TRACK_START_TIME = clendar_utils.get_calendar_time(9, 0)